name: mad_dbt

profile: mad_dbt_skanda

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  mad_dbt:
    +schema: raw

models:
  mad_dbt:
    +static_analysis: strict
    staging:
      +materialized: table
    marts:
      +materialized: table
